//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E.School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCD_TIEUCHI
    {
        public int SoPCD { get; set; }
        public int MATC { get; set; }
        public Nullable<double> Diem { get; set; }
        public string NhanXet { get; set; }
    
        public virtual PHIEU_CHAM_DIEM PHIEU_CHAM_DIEM { get; set; }
        public virtual TIEUCHI TIEUCHI { get; set; }
    }
}
